package vn.chuongpl.user_service.enums;

// Keep in sync with job-service/enums/JobCategory.java
public enum JobCategory {
    IT_SOFTWARE, FINANCE_BANKING, MARKETING, HEALTHCARE, EDUCATION,
    MANUFACTURING, RETAIL, REAL_ESTATE, TRANSPORTATION, MEDIA_ENTERTAINMENT,
    LEGAL_CONSULTING, HUMAN_RESOURCES, AGRICULTURE, ENERGY_ENVIRONMENT, HOSPITALITY_TOURISM
}
