export * from './axios-instance';

// Auth (web-candidate static spec — well-named hooks)
export * from './generated/auth/auth';
export * from './generated/users/users';

// User service — candidate, wishlist, company controllers
export * from './generated/user/candidate-controller/candidate-controller';
export * from './generated/user/wishlist-controller/wishlist-controller';
export * from './generated/user/company-controller/company-controller';
// Explicitly resolve ambiguity: company-controller's versions take the unqualified names
export { getRelatedCompanies, getGetRelatedCompaniesQueryKey, getGetRelatedCompaniesQueryOptions, useGetRelatedCompanies } from './generated/user/company-controller/company-controller';
export type { GetRelatedCompaniesQueryError, GetRelatedCompaniesQueryResult } from './generated/user/company-controller/company-controller';
// Job-specific variant (endpoint: /api/jobs/{id}/related-companies)
export { useGetRelatedCompanies as useGetJobRelatedCompanies } from './generated/job/job-controller/job-controller';
export * from './generated/user/role-controller/role-controller';
export * from './generated/user/permission-controller/permission-controller';
export * as RecruiterApi from './generated/user/recruiter-controller/recruiter-controller';
export {
  getAll2 as getAllCandidates,
  getMe2 as getCandidateProfile,
  getGetMe2QueryKey as getCandidateProfileQueryKey,
  useGetAll2 as useGetAllCandidates,
  useGetMe2 as useGetCandidateProfile,
  useUpdate2 as useUpdateCandidate,
  useUploadAvatar as useUploadCandidateAvatar,
  useUpdatePreferences1 as useUpdateCandidatePreferences,
  useGetByUserId1 as useGetCandidateByUserId,
} from './generated/user/candidate-controller/candidate-controller';
export { getMe as getRecruiterLoginUser } from './generated/user/user-controller/user-controller';
export {
  useUpdatePreferences,
  getUpdatePreferencesMutationOptions,
  updatePreferences,
  // Admin user management
  useGetAllUsers,
  getAllUsers,
  useUpdateUserStatus,
  updateUserStatus,
  useUpdateUserRoles,
  updateUserRoles,
  useDeleteUser,
  deleteUser,
  useGetMe,
} from './generated/user/user-controller/user-controller';
export type {
  UpdatePreferencesMutationResult,
  UpdatePreferencesMutationBody,
  UpdatePreferencesMutationError,
} from './generated/user/user-controller/user-controller';
export type { GetAllUsersParams, GetAllParams } from './generated/user/model';
export type { RoleResponse as UserRoleResponse } from './generated/user/model';

// Job service
export * from './generated/job/job-controller/job-controller';
export * from './generated/job/home-controller/home-controller';

// Application service
export * from './generated/application/application-controller/application-controller';
export * from './generated/application/assessment-controller/assessment-controller';
export * from './excel-import';

// AI service
export * from './generated/ai/analysis-controller/analysis-controller';
export * from './generated/ai/ai-admin-controller/ai-admin-controller';

// Manual hooks (not yet generated by Orval)
export * from './job-moderation-hooks';
export * from './user-otp-hooks';
export * from './notification-hooks';
export * from './service-package-hooks';
export * from './recruiter-applications-hooks';
export * from './assessment-manual-hooks';
export * from './google-auth';
export * from './payment-hooks';
export * from './assessment-ai-hooks';

// Job-service types not re-exported by root model
export type { JobUpdateRequest, JobResponse } from './generated/job/model';
export type { RecruiterResponse } from './generated/user/model';

// Models (root static spec)
export * from './generated/model';

// Per-service model types (namespaced to avoid collisions with root model)
export * as UserModels from './generated/user/model';
export * as JobModels from './generated/job/model';
export * as ApplicationModels from './generated/application/model';
export * as AiModels from './generated/ai/model';
