/**
 * Manual hooks for /api/users/me/send-otp and /api/users/me/verify-otp
 * These endpoints are authenticated (require Bearer token) and are not yet
 * generated by Orval, so we write them by hand following the same conventions.
 */
import { useMutation } from '@tanstack/react-query';
import type { UseMutationOptions } from '@tanstack/react-query';
import { customInstance } from './axios-instance';

const OTP_TTL_MINUTES = 5;

// ---- Request / Response types ----

export interface SendUpdateOtpRequest {
  /** Contact to send OTP to (email or phone number) */
  contact: string;
  /** "EMAIL" | "PHONE" */
  preferredVerification: string;
}

export interface VerifyUpdateOtpRequest {
  /** Contact that received the OTP */
  contact: string;
  /** "EMAIL" | "PHONE" */
  verificationType: string;
  /** 6-digit OTP code */
  code: string;
}

// ---- Raw API functions ----

export const sendUpdateOtp = (
  request: SendUpdateOtpRequest,
  options?: object,
): Promise<unknown> =>
  customInstance(
    {
      url: `/notification/api/otp/send`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: {
        target: request.contact,
        target_type: request.preferredVerification === 'PHONE' ? 'SMS' : request.preferredVerification,
        ttl_minutes: OTP_TTL_MINUTES,
      },
    },
    options,
  );

export const verifyUpdateOtp = (
  request: VerifyUpdateOtpRequest,
  options?: object,
): Promise<unknown> =>
  customInstance(
    {
      url: `/notification/api/otp/verify`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: {
        target: request.contact,
        target_type: request.verificationType === 'PHONE' ? 'SMS' : request.verificationType,
        code: request.code,
      },
    },
    options,
  );

// ---- React-Query mutation hooks ----

export const useSendUpdateOtp = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sendUpdateOtp>>,
      TError,
      { data: SendUpdateOtpRequest },
      TContext
    >;
  },
) => {
  const mutationOptions = options?.mutation ?? {};
  return useMutation<
    Awaited<ReturnType<typeof sendUpdateOtp>>,
    TError,
    { data: SendUpdateOtpRequest },
    TContext
  >({
    mutationFn: ({ data }) => sendUpdateOtp(data),
    ...mutationOptions,
  });
};

export const useVerifyUpdateOtp = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof verifyUpdateOtp>>,
      TError,
      { data: VerifyUpdateOtpRequest },
      TContext
    >;
  },
) => {
  const mutationOptions = options?.mutation ?? {};
  return useMutation<
    Awaited<ReturnType<typeof verifyUpdateOtp>>,
    TError,
    { data: VerifyUpdateOtpRequest },
    TContext
  >({
    mutationFn: ({ data }) => verifyUpdateOtp(data),
    ...mutationOptions,
  });
};
