# tests/test_rewriter.py
import shutil
from pathlib import Path
from unittest.mock import MagicMock, patch
import pytest
from docx import Document
from rewriter import (
    rewrite_chapter1,
    rewrite_chapter2,
    rewrite_chapter_heading_only,
    apply_keyword_replacements,
    KEYWORD_MAP,
)
from docx_parser import ChapterBucket, detect_chapters, get_paragraph_text
from docx.shared import Pt


def _build_doc_chapter1():
    """Minimal doc for chapter 1 testing: heading, subheading, 2 body paragraphs."""
    doc = Document()
    h1 = doc.add_paragraph("CHƯƠNG 1: GIỚI THIỆU")
    h1.style = doc.styles["Heading 1"]
    h2 = doc.add_paragraph("1.1 Tổng quan")
    h2.style = doc.styles["Heading 2"]
    doc.add_paragraph("Đoạn nội dung 1.")
    doc.add_paragraph("Đoạn nội dung 2.")
    return doc


def _build_doc_chapter2():
    doc = Document()
    h1 = doc.add_paragraph("CHƯƠNG 2: CƠ SỞ LÝ THUYẾT")
    h1.style = doc.styles["Heading 1"]
    doc.add_paragraph("Lý thuyết ban đầu.")
    doc.add_paragraph("Lý thuyết thứ hai.")
    return doc


def test_rewrite_chapter1_skips_subheadings():
    """Heading 2/3 paragraphs should not be rewritten."""
    doc = _build_doc_chapter1()
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = "new body text"

    rewrite_chapter1(doc, chapters[0], llm, "kb")

    # The Heading 2 paragraph text should be unchanged
    h2_para = doc.paragraphs[1]
    assert "1.1 Tổng quan" in get_paragraph_text(h2_para)


def test_rewrite_chapter1_rewrites_body_paragraphs():
    doc = _build_doc_chapter1()
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = "rewritten paragraph"

    rewrite_chapter1(doc, chapters[0], llm, "kb")

    # Body paragraphs (indices 2 and 3) should now contain the LLM result
    assert get_paragraph_text(doc.paragraphs[2]) == "rewritten paragraph"
    assert get_paragraph_text(doc.paragraphs[3]) == "rewritten paragraph"


def test_rewrite_chapter1_preserves_original_when_llm_returns_none():
    doc = _build_doc_chapter1()
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = None

    rewrite_chapter1(doc, chapters[0], llm, "kb")

    assert get_paragraph_text(doc.paragraphs[2]) == "Đoạn nội dung 1."
    assert get_paragraph_text(doc.paragraphs[3]) == "Đoạn nội dung 2."


def test_rewrite_chapter2_fills_first_body_paragraph():
    doc = _build_doc_chapter2()
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = "academic content generated by llm"

    rewrite_chapter2(doc, chapters[0], llm, "kb")

    assert get_paragraph_text(doc.paragraphs[1]) == "academic content generated by llm"


def test_rewrite_chapter2_clears_remaining_body_paragraphs():
    doc = _build_doc_chapter2()
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = "content"

    rewrite_chapter2(doc, chapters[0], llm, "kb")

    assert get_paragraph_text(doc.paragraphs[2]) == ""


def test_rewrite_chapter_heading_only_rewrites_heading():
    doc = Document()
    h1 = doc.add_paragraph("CHƯƠNG 3: PHÂN TÍCH HỆ THỐNG CŨ")
    h1.style = doc.styles["Heading 1"]
    doc.add_paragraph("Nội dung cũ cần xóa.")
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = "CHƯƠNG 3: PHÂN TÍCH VÀ THIẾT KẾ HỆ THỐNG SMARTCV"

    rewrite_chapter_heading_only(doc, chapters[0], llm, "kb")

    assert "SMARTCV" in get_paragraph_text(doc.paragraphs[0])


def test_rewrite_chapter_heading_only_clears_body():
    doc = Document()
    h1 = doc.add_paragraph("CHƯƠNG 3: XYZ")
    h1.style = doc.styles["Heading 1"]
    doc.add_paragraph("body to be cleared")
    chapters = detect_chapters(doc)
    llm = MagicMock()
    llm.rewrite.return_value = "new heading"

    rewrite_chapter_heading_only(doc, chapters[0], llm, "kb")

    assert get_paragraph_text(doc.paragraphs[1]) == ""


def test_apply_keyword_replacements():
    doc = Document()
    old_key = list(KEYWORD_MAP.keys())[0]
    new_val = KEYWORD_MAP[old_key]
    doc.add_paragraph(f"Tên sinh viên: {old_key}")

    apply_keyword_replacements(doc)

    assert new_val in get_paragraph_text(doc.paragraphs[0])
    assert old_key not in get_paragraph_text(doc.paragraphs[0])
